import{a as P,S,i as n}from"./assets/vendor-frHSA4Lh.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))a(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&a(u)}).observe(document,{childList:!0,subtree:!0});function t(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(r){if(r.ep)return;r.ep=!0;const o=t(r);fetch(r.href,o)}})();const b="https://pixabay.com/api/",q="50322129-1fa2d79651afdc56a0de6c955";let R=15;async function f(s,e){const t={key:q,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:R};try{return(await P.get(b,{params:t})).data}catch(a){throw console.error("Error fetching images:",a),a}}const y=document.querySelector(".gallery"),h=document.querySelector(".loader"),g=document.querySelector(".load-more"),M=new S(".gallery a",{captionsData:"alt",captionDelay:250,overlayOpacity:.8,showCounter:!1,animationSlide:!0});function L(s){const e=s.map(t=>`<li class="gallery-item">
          <a href="${t.largeImageURL}" class="gallery-link">
            <img class="gallery-img" src="${t.webformatURL}" alt="${t.tags}" />
          </a>
          <div class="gallery-stats">
            <p>Likes <span>${t.likes}</span></p>
            <p>Views <span>${t.views}</span></p>
            <p>Comments <span>${t.comments}</span></p>
            <p>Downloads <span>${t.downloads}</span></p>
          </div>
        </li>`).join("");y.insertAdjacentHTML("beforeend",e),M.refresh()}function $(){y.innerHTML=""}function w(){h.classList.add("is-active")}function v(){h.classList.remove("is-active")}function E(){g.classList.remove("hidden")}function d(){g.classList.add("hidden")}const m=document.querySelector("form.form"),B=document.querySelector('input[name="search-text"]'),O=document.querySelector(".load-more");let i=1,l="",c=0;const p=15;m.addEventListener("submit",async s=>{if(s.preventDefault(),l=B.value.trim(),i=1,$(),d(),!l){n.error({title:"Error",message:"Please enter a search query",position:"topRight"});return}w();try{const e=await f(l,i);if(e.hits.length===0){n.error({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}c=e.totalHits,L(e.hits);const t=Math.ceil(c/p);c>p?E():(d(),n.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(e){n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(e)}finally{v(),m.reset()}});O.addEventListener("click",async()=>{i+=1,w(),d();try{const s=await f(l,i);L(s.hits);const e=Math.ceil(c/p);i>=e?(d(),n.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):E();const t=document.querySelector(".gallery-item");if(t){const{height:a}=t.getBoundingClientRect();window.scrollBy({top:a*2,behavior:"smooth"})}}catch(s){n.error({title:"Error",message:"Failed to load more images. Please try again.",position:"topRight"}),console.error(s)}finally{v()}});
//# sourceMappingURL=index.js.map
