import{a as E,S as P,i as n}from"./assets/vendor-frHSA4Lh.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))a(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&a(u)}).observe(document,{childList:!0,subtree:!0});function t(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(r){if(r.ep)return;r.ep=!0;const o=t(r);fetch(r.href,o)}})();const S="https://pixabay.com/api/",b="50322129-1fa2d79651afdc56a0de6c955";let q=15;async function m(s,e){const t={key:b,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:q};try{return(await E.get(S,{params:t})).data}catch(a){throw console.error("Error fetching images:",a),a}}const f=document.querySelector(".gallery"),y=document.querySelector(".loader"),h=document.querySelector(".load-more"),R=new P(".gallery a",{captionsData:"alt",captionDelay:250,overlayOpacity:.8,showCounter:!1,animationSlide:!0});function g(s){const e=s.map(t=>`<li class="gallery-item">
          <a href="${t.largeImageURL}" class="gallery-link">
            <img class="gallery-img" src="${t.webformatURL}" alt="${t.tags}" />
          </a>
          <div class="gallery-stats">
            <p>Likes <span>${t.likes}</span></p>
            <p>Views <span>${t.views}</span></p>
            <p>Comments <span>${t.comments}</span></p>
            <p>Downloads <span>${t.downloads}</span></p>
          </div>
        </li>`).join("");f.insertAdjacentHTML("beforeend",e),R.refresh()}function M(){f.innerHTML=""}function L(){y.classList.add("is-active")}function w(){y.classList.remove("is-active")}function v(){h.classList.remove("hidden")}function d(){h.classList.add("hidden")}const $=document.querySelector("form.form"),B=document.querySelector('input[name="search-text"]'),O=document.querySelector(".load-more");let i=1,l="",c=0;const p=15;$.addEventListener("submit",async s=>{if(s.preventDefault(),l=B.value.trim(),i=1,M(),d(),!l){n.error({title:"Error",message:"Please enter a search query",position:"topRight"});return}L();try{const e=await m(l,i);if(e.hits.length===0){n.error({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}c=e.totalHits,g(e.hits);const t=Math.ceil(c/p);c>p?v():(d(),n.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(e){n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(e)}finally{w()}});O.addEventListener("click",async()=>{i+=1,L(),d();try{const s=await m(l,i);g(s.hits);const e=Math.ceil(c/p);i>=e?(d(),n.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):v();const t=document.querySelector(".gallery-item");if(t){const{height:a}=t.getBoundingClientRect();window.scrollBy({top:a*2,behavior:"smooth"})}}catch(s){n.error({title:"Error",message:"Failed to load more images. Please try again.",position:"topRight"}),console.error(s)}finally{w()}});
//# sourceMappingURL=index.js.map
